PREFIX vivo: <http://vivoweb.org/ontology/core#>

#This query counts the number of datasets available on the DCO website
SELECT (concat("Total Datasets: ", (COUNT (DISTINCT ?dataset))) as ?number) WHERE
{
?dataset a vivo:Dataset.
}