PREFIX dco: <http://info.deepcarbon.net/schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

#This query counts the number of DCO organizations that have members
#Note - This only counts for members, not all users. To count for all users, remove the ?netID line from the query.
#Stephen Moon, July 2015
SELECT (str(COUNT (DISTINCT ?country)) as ?number) WHERE
{
    ?user a foaf:Person;
        <http://vivo.mydomain.edu/ns#networkId> ?netID.
    ?user dco:inOrganization ?organization.
    ?organization obo:RO_0001025 ?country .
}

