<?php
header("Content-type: text/plain");
?>

PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX dco: <http://info.deepcarbon.net/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

DESCRIBE ?grant ?project ?pu ?ry ?community ?recipient
WHERE
{
      ?grant vitro:mostSpecificType vivo:Grant ;
          dco:grantRecipient ?recipient ;
          dco:associatedDCOCommunity ?community .
      OPTIONAL {?grant_id vivo:fundingVehicleFor ?project .}
      OPTIONAL {?project dco:hasProjectUpdate ?pu .
                ?pu dco:forReportingYear ?ry .
               }
}
