<?php

include_once("dco_common.php");

if(isset($_GET["uri"])) {
  $instance = "<" . sanitize($_GET["uri"],false) . ">";
}
else {
  twerror();
  $instance = "<?=\$instance?>" ;
}

header("Content-type: text/plain");
?>

PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dco: <http://info.deepcarbon.net/schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

describe <?=$instance?> ?community ?team ?newscard ?newsurl ?webcard ?weburl ?image ?imageloc ?doc ?author_role ?author ?journal ?area where
{
    <?=$instance?> a dco:InstrumentInitiative .
    OPTIONAL { <?=$instance?> dco:associatedDCOCommunity ?community . }
    OPTIONAL { <?=$instance?> dco:associatedDCOTeam ?team . }
    OPTIONAL {
         <?=$instance?> dco:instrInitiativeNews ?newscard .
         ?newscard vcard:hasURL ?newsurl .
    }
    OPTIONAL {
         <?=$instance?> obo:ARG_2000028 ?webcard .
         ?webcard vcard:hasURL ?weburl .
    }
    OPTIONAL {
        <?=$instance?> vitro-public:mainImage ?image .
        ?image vitro-public:downloadLocation ?imageloc .
    }
    OPTIONAL {
        <?=$instance?> dco:associatedPublication ?doc .
        ?doc vivo:relatedBy ?author_role .
        ?author_role a vivo:Authorship .
        ?author_role vivo:relates ?author .
        ?author a foaf:Person .
        OPTIONAL {
            ?doc vivo:hasPublicationVenue ?journal .
            ?journal a bibo:Journal .
        }
    }
    OPTIONAL {
        <?=$instance?> vivo:hasSubjectArea ?area .
    }
}

